#!/bin/bash
#set -x
(cd OpenFoamTurbo; wclean; wcleanLnIncludeAll)
(cd turboPerformance; wclean; wcleanLnIncludeAll)
(cd ./cgnslib_2.5;   make clean; rm -rf ./platforms ./LINUX)
(cd ./libcgnsoo_3.0; make clean; rm -rf ./platforms ./autom4te.cache)
